# -*- coding: utf-8 -*-
"""Twibot22HumanAndBotSplitting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7y7hMyH__aX9sUPWOkz_r8jG9A01A-a
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ijson --quiet

import os, csv, ijson, pandas as pd
from pathlib import Path

twibot_root = '/content/drive/MyDrive/Twibot22'
src_file    = 'tweet_8-005.json'
out_dir     = '/content/drive/MyDrive/Twibot22Split'

Path(out_dir).mkdir(parents=True, exist_ok=True)

raw = pd.read_csv(
    os.path.join(twibot_root, 'label.csv'),
    dtype=str,
    usecols=[0,1],
    names=['id','label'],
    header=None
).dropna(subset=['id','label'])

raw = raw[raw.id != 'id']
raw['id'] = raw['id'].str.lstrip('u').astype(int)

bot_ids   = set(raw.loc[raw.label=='bot','id'])
human_ids = set(raw.loc[raw.label=='human','id'])

print(f"Got {len(bot_ids):,} bot IDs and {len(human_ids):,} human IDs")

fields   = ['id','author_id','created_at','text']
base, _  = os.path.splitext(src_file)
bot_path = os.path.join(out_dir, f"{base}_bots.csv")
hum_path = os.path.join(out_dir, f"{base}_humans.csv")

total = kept_bot = kept_hum = 0

with open(os.path.join(twibot_root, src_file), 'rb') as fin, \
     open(bot_path, 'w', newline='', encoding='utf-8') as bf, \
     open(hum_path, 'w', newline='', encoding='utf-8') as hf:

    bot_w   = csv.DictWriter(bf, fields)
    human_w = csv.DictWriter(hf, fields)
    bot_w.writeheader()
    human_w.writeheader()

    for tweet in ijson.items(fin, 'item'):
        aid = tweet.get('author_id')
        if   aid in bot_ids:
            bot_w.writerow({k: tweet.get(k,'') for k in fields}); kept_bot += 1
        elif aid in human_ids:
            human_w.writerow({k: tweet.get(k,'') for k in fields}); kept_hum += 1
        total += 1

print(f"\nProcessed {total:,} tweets → {kept_bot:,} bots, {kept_hum:,} humans")
print("Bot CSV:  ", bot_path)
print("Human CSV:", hum_path)

import pandas as pd

bot_csv   = '/content/drive/MyDrive/Twibot22Split/tweet_0-010_bots.csv'
human_csv = '/content/drive/MyDrive/Twibot22Split/tweet_0-010_humans.csv'

bot_sample   = pd.read_csv(bot_csv,   nrows=20)
human_sample = pd.read_csv(human_csv, nrows=5)

print("=== Bot tweets sample ===")
print(bot_sample.to_string(index=False))

src_dir   = '/content/drive/MyDrive/Twibot22Split'
pattern   = '*_humans.csv'
out_csv   = '/content/drive/MyDrive/Twibot22Split/human_tweets.csv'

import os, glob, pandas as pd

csv_list = sorted(glob.glob(os.path.join(src_dir, pattern)))
print(f"Found {len(csv_list)} files -> {out_csv}")

first_file = True
for f_idx, path in enumerate(csv_list, 1):
    print(f"  • [{f_idx}/{len(csv_list)}]  appending {os.path.basename(path)}")

    for chunk in pd.read_csv(path, chunksize=100_000):
        chunk.to_csv(
            out_csv,
            mode='w' if first_file else 'a',
            header=first_file,
            index=False
        )
        first_file = False

print("\n✅ Done — combined file saved to:", out_csv)